### ISSUE TITLE
the start_notebook.sh is not working

### ISSUE THREAD

**Issue by tandermann** [outlierbio/ob-project-template#1]
it seems that the specified docker repo (ob-project-template-master) does not exist, where can I find it?

**Comment by jfeala** [comment]
Sorry, this got a bit outdated. I updated the Dockerfile to pull from the latest R image provided by Jupyter. Let me know if you still have trouble

**Comment by tandermann** [comment]
it works fine now, thanks a lot for fixing it so quickly, that helped a lot!

**Comment by tandermann** [comment]
> Read the project guidelines in the notebook

are there supposed to be guidelines in the notebook that opens automatically after executing the start_notebook.sh command?
In my case it opens a completely empty notebook, after entering the token...

**Comment by jfeala** [comment]
Ok pull the latest master and try now, the work folder location went stale, since their last update of the base notebook image
